# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print('The version of numpy is', np.__version__)                 #np.__version__ to get the version of numpy
print('The configuration for numpy is', np.show_config())        #np.show_config() to get configuration

The version of numpy is 1.20.3
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/meganfirgard/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/meganfirgard/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/meganfirgard/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/meganfirgard/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/meganfirgard/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/meganfirgard/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/meganfirgard/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/meganfirgard/opt/anaco

#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
x = np.zeros(10)         #use np.zeros to make a null vector
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
print('The size of the array: ', x.size)
print('The memory size of one array element in bytes', x.itemsize)
print('The memory size of the entire array in bytes', x.size * x.itemsize)

The size of the array:  10
The memory size of one array element in bytes 8
The memory size of the entire array in bytes 80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
print(np.info(np.add))   #np.info() w whatever "np." function you're interested inside the paratheses
                            

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
y = np.zeros(10)
y[5] = 1                 #use [] brackets to indicate term(s) in an array 
print(y)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
z = np.linspace(10, 49, 40)     #used np.linspace to pick starting value, ending value, and then figure out # elements
print(z)                        #also could've used np.arange. probs easier lol

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49.]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [44]:
x = np.arange(0, 10)            #make array with np.arange
print('The original array:', x)   

new_x = x[:: -1]                #new array with reverse order by slice notation with a step of -1
print('The reversed array:', new_x)

The original array: [0 1 2 3 4 5 6 7 8 9]
The reversed array: [9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [23]:
y = np.arange(0, 9).reshape(3,3)        #np.arange(1st element, last element).reshape(matrix size)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [34]:
z = [1, 2, 0, 0, 4, 0]
print('The non-zero elements of the array, z, are at indices: ', np.nonzero(z))
#np.nonzero will give the index number for the terms in the array that are not zero

The non-zero elements of the array, z, are at indices:  (array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [32]:
y = np.zeros(9).reshape(3,3) #used the same reshape method as before for the 3x3 matrix, but with np.zeros
y[0,0] = 1                   #then used brackets to pick the indices to change to 1
y[1,1] = 1
y[2,2] = 1
print('Here is a 3x3 identity matrix:')
print(y)

Here is a 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
z = np.random.random((3, 3, 3)) #the np.random.random() does the random numbers
print(z)                        #the (3, 3, 3) indicates a 3x3x3 matrix in that function

[[[0.01179243 0.35106945 0.13032452]
  [0.96485675 0.40364766 0.49298751]
  [0.6383292  0.50684787 0.97522289]]

 [[0.18161735 0.48024623 0.870501  ]
  [0.07507893 0.23187734 0.0403867 ]
  [0.6001461  0.91038505 0.83468617]]

 [[0.08217604 0.96417107 0.22751883]
  [0.66924282 0.31362071 0.35437887]
  [0.38079359 0.72664149 0.39994556]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [40]:
z = np.random.random((10, 10))
print(z)

minimum = np.min(z)
maximum = np.max(z)

print('The minimum value of the matrix, z, is: ', minimum)
print('The maximum value of the matrix, z, is: ', maximum)

[[0.88288687 0.58130155 0.24287633 0.12454927 0.49743306 0.01504591
  0.91112385 0.49168006 0.7434746  0.72604583]
 [0.08132148 0.41054555 0.70106848 0.89911885 0.39101271 0.54645563
  0.85680537 0.96958106 0.62248984 0.31799007]
 [0.700263   0.48755197 0.25778617 0.27378203 0.58063869 0.11339064
  0.23449944 0.13921696 0.73205934 0.50274116]
 [0.70055437 0.75725227 0.4870517  0.43281471 0.64520105 0.70155296
  0.53533008 0.22435172 0.69738326 0.52255924]
 [0.40419769 0.11406809 0.44732108 0.34987154 0.91603262 0.9945236
  0.51163017 0.61894285 0.66749383 0.49505454]
 [0.72785345 0.77374153 0.17248374 0.44154243 0.52938697 0.87765361
  0.97327179 0.11551447 0.7789826  0.2884052 ]
 [0.21002598 0.09208065 0.15994095 0.55060216 0.24574857 0.29737904
  0.5606859  0.94022089 0.23380821 0.49845857]
 [0.40757099 0.66623876 0.29654157 0.3596119  0.27795153 0.88619026
  0.1470751  0.66856274 0.54678651 0.04861587]
 [0.99402314 0.48610469 0.52391946 0.98156458 0.77490744 0.96687158
  0.28143268 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [43]:
x = np.random.random(30)
print(x)

mean = np.mean(x)
print('The mean of the randomized array, x, is: ', mean)

[0.98736745 0.71965756 0.75783957 0.22230577 0.33141529 0.71912083
 0.46554458 0.265469   0.27638122 0.16094673 0.58035986 0.50909401
 0.87906145 0.56761106 0.5567931  0.48863548 0.72839691 0.67655859
 0.27231662 0.18217604 0.33088817 0.35988141 0.32328449 0.5835237
 0.28790903 0.97797021 0.62744033 0.54571139 0.24809375 0.48030627]
The mean of the randomized array, x, is:  0.503735329151383


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [46]:
x = np.ones((5, 5))
print('A 2D array, x, of ones:\n', x)
x[1:-1, 1:-1] = 0
print('The 2D array, x, with ones bordering a center of zeros:\n', x)

A 2D array, x, of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
The 2D array, x, with ones bordering a center of zeros:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [48]:
y = np.ones((3, 3))
print('The original 2D array of ones:\n', y)

y = np.pad(y, pad_width = 1, mode = 'constant', constant_values = 0) #np.pad for adding a border of specific width
                                                                     #and value around and existing array
print('The 2D array of ones surrounded by a border of zeros:\n', y)

The original 2D array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
The 2D array of ones surrounded by a border of zeros:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [51]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
print('The result is:', 0.3 == 3 * 0.1)

The result is: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [59]:
x = np.zeros(25).reshape(5, 5)
x[1, 0] = 1
x[2, 1] = 2
x[3, 2] = 3
x[4, 3] = 4
print('The matrix is:\n', x)

#the more streamlined version of this:
X = np.diag(1 + np.arange(4), k = -1)
print('Using the more streamlined approach, we get:\n', X)

The matrix is:
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
Using the more streamlined approach, we get:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [61]:
y = np.zeros((8, 8))
y[1::2, ::2] = 1     #Assign value 1 (=) to every other element in every other row, starting from the second row
y[::2, 1::2] = 1     #Assign value 1 (=) to every other element in every other column, starting from the second column
print('An 8x8 matrix with a checkerboard pattern:\n', y)

An 8x8 matrix with a checkerboard pattern:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [62]:
print(np.unravel_index(99,(6,7,8))) 
#np.unravel_index(index # interested in, shape of array (x, y, z))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [64]:
z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print('Checkerboard matrix using tile function:\n', z)

Checkerboard matrix using tile function:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [67]:
x = np.random.random((5, 5))                                  #make 5x5 randomized matrix
col_means = np.mean(x, axis = 0)                              #take the mean of each columns
x_normalized = (x - col_means) / np.std(x, axis = 0)          #normalize each column by subtracting the mean from each
print('The normalized 5x5 random matrix is:\n', x_normalized) #& dividing by its standard deviation 

The normalized 5x5 random matrix is:
 [[-1.88442906  0.91835438 -1.35648259 -0.61573078  1.40829856]
 [-0.15504858  1.26600129  0.68135121  1.52749309 -0.34928593]
 [ 0.57817134 -0.93708605 -1.07712397 -1.45144718 -1.02455982]
 [ 0.62365567 -1.29367024  0.86347703  0.40271772 -0.97753318]
 [ 0.83765063  0.04640061  0.88877832  0.13696715  0.94308037]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [68]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/var/folders/zm/hhgk9ysn1p7fc83k_tr1x36m0000gn/T/ipykernel_47532/2911720781.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [69]:
x = np.random.random((5, 3))
print('The 5x3 random matrix is:\n', x)

y = np.random.random((3, 2))
print('The 3x2 random matrix is:\n', y)

z = np.dot(x, y)
print('The dot product of the two matrices is:\n', z)

The 5x3 random matrix is:
 [[0.409156   0.03092319 0.31265291]
 [0.54206899 0.21071308 0.51957661]
 [0.35151753 0.49910829 0.34294718]
 [0.01231983 0.87547403 0.46888836]
 [0.5657167  0.34799249 0.37532243]]
The 3x2 random matrix is:
 [[0.82236828 0.40903568]
 [0.5243095  0.09882903]
 [0.4968381  0.54140398]]
The dot product of the two matrices is:
 [[0.50802812 0.33968704]
 [0.81440467 0.52385097]
 [0.72115331 0.37878257]
 [0.70211239 0.34541952]
 [0.83415772 0.46899113]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [73]:
z = np.arange(11)
z[(3 < z) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)